### ISSUE TITLE
Decrypted buffer is empty

### ISSUE THREAD

**Issue by ghost** [Nk125/Chromium-Stealer#2]
![image](https://user-images.githubusercontent.com/109090507/178291673-8477e9bc-036d-410b-a462-312d4342fd46.png)
Release/x86
I think problem in gcm decryption

**Comment by Nk125** [comment]
You can check if the password has any data in Chrome? By the size of encrypted password seems like it's just a padded empty string, if the aes decrypt has problems i can publish the entire configured project to debug it in any pc

**Comment by Jimvcarry** [comment]
> You can check if the password has any data in Chrome? By the size of encrypted password seems like it's just a padded empty string, if the aes decrypt has problems i can publish the entire configured project to debug it in any pc

your program output the correct password, compiled by me does not output anything
btw another data(iv,auth_tag,encrypted password) are same
![image](https://user-images.githubusercontent.com/109090507/178417417-4253490a-c6a9-491c-b409-cd93a2a1dcc6.png)

**Comment by Jimvcarry** [comment]
fixED aes.set_iv(reinterpret_cast<unsigned char*>(iv.data())); must be replaced to aes.set_nonce(reinterpret_cast<unsigned char*>(iv.data()));

**Comment by RazenIW** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/51978603/208166121-b20edf72-02ff-408c-9690-e9ffb7be9ce1.png)
